import numpy as np

PROBLEMS = [
    {"desc": "Import numpy as np", "answer_code": "import numpy as np"},
    {"desc": "Create a null vector of size 10", "answer_code": "np.zeros(10)"},
    {"desc": "Create a vector with values ranging from 10 to 49", "answer_code": "np.arange(10,50)"},
    {"desc": "Reverse a vector (first element becomes last)", "answer_code": "np.arange(50)[::-1]"},
    {"desc": "Create a 3x3 matrix with values ranging from 0 to 8", "answer_code": "np.arange(9).reshape(3,3)"},
    {"desc": "Find indices of non-zero elements from [1,2,0,0,4,0]", "answer_code": "np.nonzero([1,2,0,0,4,0])"},
    {"desc": "Create a 3x3 identity matrix", "answer_code": "np.eye(3)"},
    {"desc": "Create a 3x3x3 array with random values", "answer_code": "np.random.random((3,3,3))"},
    {"desc": "Create a 10x10 array with random values and find min/max", "answer_code": "np.random.random((10,10))"},
    {"desc": "Create a random vector of size 30 and find mean", "answer_code": "np.random.random(30)"},
    {"desc": "Create a 2d array with 1 on border and 0 inside", "answer_code": "np.ones((10,10)); Z[1:-1,1:-1] = 0"},
    {"desc": "Create a 5x5 matrix with row values ranging from 0 to 4", "answer_code": "np.zeros((5,5)) + np.arange(5)"},
    {"desc": "Create a vector of size 10 with values ranging from 0 to 1, both excluded", "answer_code": "np.linspace(0,1,11,endpoint=False)[1:]"},
    {"desc": "Create a random vector of size 10 and sort it", "answer_code": "np.sort(np.random.random(10))"},
    {"desc": "Create a 2D array subclass such that Z[i,j] == Z[j,i]", "answer_code": "np.array([[1,2,3],[2,4,5],[3,5,6]])"},
    {"desc": "Consider a 16x16 array, get the block-sum (block size is 4x4)", "answer_code": "np.ones((16,16))"},
    {"desc": "How to get the n largest values of an array", "answer_code": "np.random.randint(0,100,100)"},
    {"desc": "Create a record array from a regular array", "answer_code": "np.array([('Hello', 2.5, 3), ('World', 3.6, 2)])"},
    {"desc": "Consider a large vector Z, compute Z to the power of 3", "answer_code": "np.random.rand(1000)"},
    {"desc": "Consider two arrays A and B of shape (8,3) and (2,2)", "answer_code": "np.random.randint(0,5,(8,3))"},
    {"desc": "Considering a 10x3 matrix, extract rows with unequal values", "answer_code": "np.random.randint(0,5,(10,3))"},
    {"desc": "Convert a vector of ints into a matrix binary representation", "answer_code": "np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])"},
    {"desc": "Given a two dimensional array, extract unique rows", "answer_code": "np.random.randint(0,2,(6,3))"},
    {"desc": "Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul", "answer_code": "np.random.uniform(0,1,10)"},
    {"desc": "How to implement the Game of Life using numpy arrays", "answer_code": "np.random.randint(0,2,(50,50))"},
    {"desc": "How to get the diagonal of a dot product", "answer_code": "np.random.uniform(0,1,(5,5))"},
    {"desc": "Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value", "answer_code": "np.array([1,2,3,4,5])"},
    {"desc": "Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)", "answer_code": "np.ones((5,5,3))"},
    {"desc": "How to swap two rows of an array", "answer_code": "np.arange(25).reshape(5,5)"},
    {"desc": "Consider a set of 10 triplets describing 10 triangles, find the set of unique line segments", "answer_code": "np.random.randint(0,100,(10,3))"},
    {"desc": "Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C", "answer_code": "np.bincount([1,1,2,3,4,4,6])"},
    {"desc": "How to compute averages using a sliding window over an array", "answer_code": "np.arange(20)"},
    {"desc": "Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1", "answer_code": "np.arange(10)"},
    {"desc": "How to negate a boolean, or to change the sign of a float inplace", "answer_code": "np.random.randint(0,2,100)"},
    {"desc": "Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i", "answer_code": "np.random.uniform(-10,10,(10,2))"},
    {"desc": "Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i", "answer_code": "np.random.uniform(-10,10,(10,2))"},
    {"desc": "Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element", "answer_code": "np.random.randint(0,10,(10,10))"},
    {"desc": "Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]", "answer_code": "np.arange(1,15,dtype=np.uint32)"},
    {"desc": "Compute a matrix rank", "answer_code": "np.random.uniform(0,1,(10,10))"},
    {"desc": "How to find the most frequent value in an array", "answer_code": "np.random.randint(0,10,50)"},
    {"desc": "Extract all the contiguous 3x3 blocks from a random 10x10 matrix", "answer_code": "np.random.randint(0,5,(10,10))"},
    {"desc": "Create a 2D array subclass such that Z[i,j] == Z[j,i]", "answer_code": "np.random.randint(0,10,(5,5))"},
    {"desc": "Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once", "answer_code": "np.ones((10,20,20))"},
    {"desc": "Consider a 16x16 array, how to get the block-sum (block size is 4x4)", "answer_code": "np.ones((16,16))"},
    {"desc": "How to implement the Game of Life using numpy arrays", "answer_code": "np.random.randint(0,2,(50,50))"},
    {"desc": "How to get the n largest values of an array", "answer_code": "np.arange(10000)"},
    {"desc": "Given an arbitrary number of vectors, build the cartesian product (every combination of every item)", "answer_code": "([1, 2, 3], [4, 5], [6, 7])"},
    {"desc": "How to create a record array from a regular array", "answer_code": "np.array([('Hello', 2.5, 3), ('World', 3.6, 2)])"},
    {"desc": "Consider a large vector Z, compute Z to the power of 3 using 3 different methods", "answer_code": "np.random.rand(int(5e7))"},
    {"desc": "Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B", "answer_code": "np.random.randint(0,5,(8,3))"},
    {"desc": "Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])", "answer_code": "np.random.randint(0,5,(10,3))"},
    {"desc": "Convert a vector of ints into a matrix binary representation", "answer_code": "np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])"},
    {"desc": "Given a two dimensional array, how to extract unique rows", "answer_code": "np.random.randint(0,2,(6,3))"},
    {"desc": "Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function", "answer_code": "np.random.uniform(0,1,10)"},
    {"desc": "Considering a path described by two vectors (X,Y), how to sample it using equidistant samples", "answer_code": "np.arange(0, 10*np.pi, 0.1)"},
    {"desc": "Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees", "answer_code": "np.array([[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0], [1.5, 2.5, 1.0, 0.0]])"},
    {"desc": "Compute bootstrapped 95% confidence intervals for the mean of a 1D array X", "answer_code": "np.random.randn(100)"}
] 